import { cellsFor, headersFor } from './format';
import type { AnyExportDataset } from './types';

/**
 * RFC 4180 quoting: wrap in double quotes when the value contains a comma,
 * quote, CR or LF, and double any embedded quotes.
 */
export function escapeCsvValue(value: string): string {
  if (value === '') return '';

  // A leading =, +, - or @ makes Excel and Sheets treat the cell as a formula.
  // Prefixing with a tab neutralises that without altering the visible text.
  const guarded = /^[=+\-@\t\r]/.test(value) ? `\t${value}` : value;

  // Tab is included so a guarded value is always quoted: some parsers treat a
  // bare tab as a delimiter, and quoting keeps the guard from splitting a cell.
  if (/[",\r\n\t]/.test(guarded)) {
    return `"${guarded.replace(/"/g, '""')}"`;
  }
  return guarded;
}

export function toCsvRow(values: string[]): string {
  return values.map(escapeCsvValue).join(',');
}

/**
 * Emits a header block (title, filters, sort, provenance) above the table so a
 * downloaded file still says what it is and how it was filtered. Excel opens
 * this cleanly; the blank line separates preamble from the data grid.
 */
export function toCsv(
  dataset: AnyExportDataset,
  options: { preamble?: boolean; summary?: boolean } = {},
): string {
  const { meta, columns, rows, summary } = dataset;
  const lines: string[] = [];

  if (options.preamble !== false) {
    lines.push(toCsvRow([meta.title]));
    if (meta.subtitle) lines.push(toCsvRow([meta.subtitle]));

    for (const filter of meta.filters) {
      lines.push(toCsvRow([filter.label, filter.value]));
    }
    if (meta.sort) lines.push(toCsvRow(['Sorted by', meta.sort]));

    lines.push(toCsvRow(['Rows', String(rows.length)]));
    lines.push(toCsvRow(['Generated', meta.generatedAt.toISOString()]));
    lines.push(toCsvRow(['Generated by', meta.generatedBy]));
    lines.push('');
  }

  lines.push(toCsvRow(headersFor(columns)));

  for (const row of rows) {
    lines.push(toCsvRow(cellsFor(columns, row)));
  }

  if (options.summary !== false && summary && summary.length > 0) {
    lines.push('');
    for (const entry of summary) {
      lines.push(toCsvRow([entry.label, entry.value]));
    }
  }

  // CRLF is what Excel expects; the BOM stops it mangling non-ASCII names.
  return `﻿${lines.join('\r\n')}\r\n`;
}
